// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: common/telemetry/ardk_telemetry.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Niantic.ARDK.AR.Protobuf {

  /// <summary>Holder for reflection information generated from common/telemetry/ardk_telemetry.proto</summary>
  public static partial class ArdkTelemetryReflection {

    #region Descriptor
    /// <summary>File descriptor for common/telemetry/ardk_telemetry.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ArdkTelemetryReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiVjb21tb24vdGVsZW1ldHJ5L2FyZGtfdGVsZW1ldHJ5LnByb3RvEg1uYXIu",
            "dGVsZW1ldHJ5Gh9jb21tb24vYXJfY29tbW9uX21ldGFkYXRhLnByb3RvGh9n",
            "b29nbGUvcHJvdG9idWYvdGltZXN0YW1wLnByb3RvIqcEChZBUkRLVGVsZW1l",
            "dHJ5T21uaVByb3RvEkIKFGluaXRpYWxpemF0aW9uX2V2ZW50GAEgASgLMiIu",
            "bmFyLnRlbGVtZXRyeS5Jbml0aWFsaXphdGlvbkV2ZW50SAASOQoQYXJfc2Vz",
            "c2lvbl9ldmVudBgCIAEoCzIdLm5hci50ZWxlbWV0cnkuQVJTZXNzaW9uRXZl",
            "bnRIABJHChdsaWdodHNoaXBfc2VydmljZV9ldmVudBgDIAEoCzIkLm5hci50",
            "ZWxlbWV0cnkuTGlnaHRzaGlwU2VydmljZUV2ZW50SAASUQocbXVsdGlwbGF5",
            "ZXJfY29ubmVjdGlvbl9ldmVudBgEIAEoCzIpLm5hci50ZWxlbWV0cnkuTXVs",
            "dGlwbGF5ZXJDb25uZWN0aW9uRXZlbnRIABJbCiFlbmFibGVfY29udGV4dHVh",
            "bF9hd2FyZW5lc3NfZXZlbnQYBSABKAsyLi5uYXIudGVsZW1ldHJ5LkVuYWJs",
            "ZWRDb250ZXh0dWFsQXdhcmVuZXNzRXZlbnRIABI6ChBjb21tb25fbWV0YV9k",
            "YXRhGOgHIAEoCzIfLm5hci50ZWxlbWV0cnkuQVJDb21tb25NZXRhZGF0YRIW",
            "Cg1kZXZlbG9wZXJfa2V5GOkHIAEoCRIuCgl0aW1lc3RhbXAY6gcgASgLMhou",
            "Z29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcEIRCg90ZWxlbWV0cnlfZXZlbnQi",
            "QgoTSW5pdGlhbGl6YXRpb25FdmVudBIUCgxpbnN0YWxsX21vZGUYASABKAkS",
            "FQoNbG9jYWxlX3JlZ2lvbhgCIAEoCSKlAQoOQVJTZXNzaW9uRXZlbnQSOgoN",
            "c2Vzc2lvbl9zdGF0ZRgBIAEoDjIjLm5hci50ZWxlbWV0cnkuQVJTZXNzaW9u",
            "RXZlbnQuU3RhdGUSEgoKc2Vzc2lvbl9pZBgCIAEoCSJDCgVTdGF0ZRILCgdV",
            "TktOT1dOEAASCwoHQ1JFQVRFRBABEgcKA1JVThACEgkKBVBBVVNFEAMSDAoI",
            "RElTUE9TRUQQBCIXChVMaWdodHNoaXBTZXJ2aWNlRXZlbnQi2QMKGk11bHRp",
            "cGxheWVyQ29ubmVjdGlvbkV2ZW50EkoKCmNvbm5lY3Rpb24YASABKA4yNi5u",
            "YXIudGVsZW1ldHJ5Lk11bHRpcGxheWVyQ29ubmVjdGlvbkV2ZW50LkNvbm5l",
            "Y3RTdGF0ZRIhChlhcmJlX3Nlc3NzaW9uX2luc3RhbmNlX2lkGAIgASgJEhIK",
            "CnNlc3Npb25faWQYAyABKAkSRwoKcGVlcl9zdGF0ZRgEIAEoDjIzLm5hci50",
            "ZWxlbWV0cnkuTXVsdGlwbGF5ZXJDb25uZWN0aW9uRXZlbnQuUGVlclN0YXRl",
            "IlMKDENvbm5lY3RTdGF0ZRILCgdVTktOT1dOEAASCQoFU1RBUlQQARIICgRK",
            "T0lOEAISDQoJQ09OTkVDVEVEEAMSCQoFTEVBVkUQBBIHCgNFTkQQBSKZAQoJ",
            "UGVlclN0YXRlEhEKDVNUQVRFX1VOS05PV04QABIQCgxJTklUSUFMSVpJTkcQ",
            "ARIhCh1XQUlUSU5HX0ZPUl9MT0NBTElaQVRJT05fREFUQRACEg4KCkxPQ0FM",
            "SVpJTkcQAxIPCgtTVEFCSUxJWklORxAEEgoKBlNUQUJMRRAFEgsKB0xJTUlU",
            "RUQQBhIKCgZGQUlMRUQQByJkCh9FbmFibGVkQ29udGV4dHVhbEF3YXJlbmVz",
            "c0V2ZW50Eg8KB21lc2hpbmcYASABKAgSDgoGZnVzaW9uGAIgASgIEg0KBWRl",
            "cHRoGAMgASgIEhEKCXNlbWFudGljcxgEIAEoCEJWCiFjb20ubmlhbnRpY3By",
            "b2plY3QuYXJkay50ZWxlbWV0cnlaFm5pYW50aWMvYXJkay90ZWxlbWV0cnmq",
            "AhhOaWFudGljLkFSREsuQVIuUHJvdG9idWZiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Niantic.ARDK.AR.Protobuf.ArCommonMetadataReflection.Descriptor, global::Google.Protobuf.WellKnownTypes.TimestampReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Niantic.ARDK.AR.Protobuf.ARDKTelemetryOmniProto), global::Niantic.ARDK.AR.Protobuf.ARDKTelemetryOmniProto.Parser, new[]{ "InitializationEvent", "ArSessionEvent", "LightshipServiceEvent", "MultiplayerConnectionEvent", "EnableContextualAwarenessEvent", "CommonMetaData", "DeveloperKey", "Timestamp" }, new[]{ "TelemetryEvent" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Niantic.ARDK.AR.Protobuf.InitializationEvent), global::Niantic.ARDK.AR.Protobuf.InitializationEvent.Parser, new[]{ "InstallMode", "LocaleRegion" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Niantic.ARDK.AR.Protobuf.ARSessionEvent), global::Niantic.ARDK.AR.Protobuf.ARSessionEvent.Parser, new[]{ "SessionState", "SessionId" }, null, new[]{ typeof(global::Niantic.ARDK.AR.Protobuf.ARSessionEvent.Types.State) }, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Niantic.ARDK.AR.Protobuf.LightshipServiceEvent), global::Niantic.ARDK.AR.Protobuf.LightshipServiceEvent.Parser, null, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Niantic.ARDK.AR.Protobuf.MultiplayerConnectionEvent), global::Niantic.ARDK.AR.Protobuf.MultiplayerConnectionEvent.Parser, new[]{ "Connection", "ArbeSesssionInstanceId", "SessionId", "PeerState" }, null, new[]{ typeof(global::Niantic.ARDK.AR.Protobuf.MultiplayerConnectionEvent.Types.ConnectState), typeof(global::Niantic.ARDK.AR.Protobuf.MultiplayerConnectionEvent.Types.PeerState) }, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Niantic.ARDK.AR.Protobuf.EnabledContextualAwarenessEvent), global::Niantic.ARDK.AR.Protobuf.EnabledContextualAwarenessEvent.Parser, new[]{ "Meshing", "Fusion", "Depth", "Semantics" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class ARDKTelemetryOmniProto : pb::IMessage<ARDKTelemetryOmniProto>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ARDKTelemetryOmniProto> _parser = new pb::MessageParser<ARDKTelemetryOmniProto>(() => new ARDKTelemetryOmniProto());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ARDKTelemetryOmniProto> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Niantic.ARDK.AR.Protobuf.ArdkTelemetryReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ARDKTelemetryOmniProto() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ARDKTelemetryOmniProto(ARDKTelemetryOmniProto other) : this() {
      commonMetaData_ = other.commonMetaData_ != null ? other.commonMetaData_.Clone() : null;
      developerKey_ = other.developerKey_;
      timestamp_ = other.timestamp_ != null ? other.timestamp_.Clone() : null;
      switch (other.TelemetryEventCase) {
        case TelemetryEventOneofCase.InitializationEvent:
          InitializationEvent = other.InitializationEvent.Clone();
          break;
        case TelemetryEventOneofCase.ArSessionEvent:
          ArSessionEvent = other.ArSessionEvent.Clone();
          break;
        case TelemetryEventOneofCase.LightshipServiceEvent:
          LightshipServiceEvent = other.LightshipServiceEvent.Clone();
          break;
        case TelemetryEventOneofCase.MultiplayerConnectionEvent:
          MultiplayerConnectionEvent = other.MultiplayerConnectionEvent.Clone();
          break;
        case TelemetryEventOneofCase.EnableContextualAwarenessEvent:
          EnableContextualAwarenessEvent = other.EnableContextualAwarenessEvent.Clone();
          break;
      }

      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ARDKTelemetryOmniProto Clone() {
      return new ARDKTelemetryOmniProto(this);
    }

    /// <summary>Field number for the "initialization_event" field.</summary>
    public const int InitializationEventFieldNumber = 1;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Niantic.ARDK.AR.Protobuf.InitializationEvent InitializationEvent {
      get { return telemetryEventCase_ == TelemetryEventOneofCase.InitializationEvent ? (global::Niantic.ARDK.AR.Protobuf.InitializationEvent) telemetryEvent_ : null; }
      set {
        telemetryEvent_ = value;
        telemetryEventCase_ = value == null ? TelemetryEventOneofCase.None : TelemetryEventOneofCase.InitializationEvent;
      }
    }

    /// <summary>Field number for the "ar_session_event" field.</summary>
    public const int ArSessionEventFieldNumber = 2;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Niantic.ARDK.AR.Protobuf.ARSessionEvent ArSessionEvent {
      get { return telemetryEventCase_ == TelemetryEventOneofCase.ArSessionEvent ? (global::Niantic.ARDK.AR.Protobuf.ARSessionEvent) telemetryEvent_ : null; }
      set {
        telemetryEvent_ = value;
        telemetryEventCase_ = value == null ? TelemetryEventOneofCase.None : TelemetryEventOneofCase.ArSessionEvent;
      }
    }

    /// <summary>Field number for the "lightship_service_event" field.</summary>
    public const int LightshipServiceEventFieldNumber = 3;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Niantic.ARDK.AR.Protobuf.LightshipServiceEvent LightshipServiceEvent {
      get { return telemetryEventCase_ == TelemetryEventOneofCase.LightshipServiceEvent ? (global::Niantic.ARDK.AR.Protobuf.LightshipServiceEvent) telemetryEvent_ : null; }
      set {
        telemetryEvent_ = value;
        telemetryEventCase_ = value == null ? TelemetryEventOneofCase.None : TelemetryEventOneofCase.LightshipServiceEvent;
      }
    }

    /// <summary>Field number for the "multiplayer_connection_event" field.</summary>
    public const int MultiplayerConnectionEventFieldNumber = 4;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Niantic.ARDK.AR.Protobuf.MultiplayerConnectionEvent MultiplayerConnectionEvent {
      get { return telemetryEventCase_ == TelemetryEventOneofCase.MultiplayerConnectionEvent ? (global::Niantic.ARDK.AR.Protobuf.MultiplayerConnectionEvent) telemetryEvent_ : null; }
      set {
        telemetryEvent_ = value;
        telemetryEventCase_ = value == null ? TelemetryEventOneofCase.None : TelemetryEventOneofCase.MultiplayerConnectionEvent;
      }
    }

    /// <summary>Field number for the "enable_contextual_awareness_event" field.</summary>
    public const int EnableContextualAwarenessEventFieldNumber = 5;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Niantic.ARDK.AR.Protobuf.EnabledContextualAwarenessEvent EnableContextualAwarenessEvent {
      get { return telemetryEventCase_ == TelemetryEventOneofCase.EnableContextualAwarenessEvent ? (global::Niantic.ARDK.AR.Protobuf.EnabledContextualAwarenessEvent) telemetryEvent_ : null; }
      set {
        telemetryEvent_ = value;
        telemetryEventCase_ = value == null ? TelemetryEventOneofCase.None : TelemetryEventOneofCase.EnableContextualAwarenessEvent;
      }
    }

    /// <summary>Field number for the "common_meta_data" field.</summary>
    public const int CommonMetaDataFieldNumber = 1000;
    private global::Niantic.ARDK.AR.Protobuf.ARCommonMetadata commonMetaData_;
    /// <summary>
    /// Common meta data for all the telemetry protos. The field will be filled in on Unity.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Niantic.ARDK.AR.Protobuf.ARCommonMetadata CommonMetaData {
      get { return commonMetaData_; }
      set {
        commonMetaData_ = value;
      }
    }

    /// <summary>Field number for the "developer_key" field.</summary>
    public const int DeveloperKeyFieldNumber = 1001;
    private string developerKey_ = "";
    /// <summary>
    /// Active developer key
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string DeveloperKey {
      get { return developerKey_; }
      set {
        developerKey_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "timestamp" field.</summary>
    public const int TimestampFieldNumber = 1002;
    private global::Google.Protobuf.WellKnownTypes.Timestamp timestamp_;
    /// <summary>
    /// Timestamp from the current device representing a point in time independent of any time zone or calendar.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Protobuf.WellKnownTypes.Timestamp Timestamp {
      get { return timestamp_; }
      set {
        timestamp_ = value;
      }
    }

    private object telemetryEvent_;
    /// <summary>Enum of possible cases for the "telemetry_event" oneof.</summary>
    public enum TelemetryEventOneofCase {
      None = 0,
      InitializationEvent = 1,
      ArSessionEvent = 2,
      LightshipServiceEvent = 3,
      MultiplayerConnectionEvent = 4,
      EnableContextualAwarenessEvent = 5,
    }
    private TelemetryEventOneofCase telemetryEventCase_ = TelemetryEventOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TelemetryEventOneofCase TelemetryEventCase {
      get { return telemetryEventCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearTelemetryEvent() {
      telemetryEventCase_ = TelemetryEventOneofCase.None;
      telemetryEvent_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ARDKTelemetryOmniProto);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ARDKTelemetryOmniProto other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(InitializationEvent, other.InitializationEvent)) return false;
      if (!object.Equals(ArSessionEvent, other.ArSessionEvent)) return false;
      if (!object.Equals(LightshipServiceEvent, other.LightshipServiceEvent)) return false;
      if (!object.Equals(MultiplayerConnectionEvent, other.MultiplayerConnectionEvent)) return false;
      if (!object.Equals(EnableContextualAwarenessEvent, other.EnableContextualAwarenessEvent)) return false;
      if (!object.Equals(CommonMetaData, other.CommonMetaData)) return false;
      if (DeveloperKey != other.DeveloperKey) return false;
      if (!object.Equals(Timestamp, other.Timestamp)) return false;
      if (TelemetryEventCase != other.TelemetryEventCase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (telemetryEventCase_ == TelemetryEventOneofCase.InitializationEvent) hash ^= InitializationEvent.GetHashCode();
      if (telemetryEventCase_ == TelemetryEventOneofCase.ArSessionEvent) hash ^= ArSessionEvent.GetHashCode();
      if (telemetryEventCase_ == TelemetryEventOneofCase.LightshipServiceEvent) hash ^= LightshipServiceEvent.GetHashCode();
      if (telemetryEventCase_ == TelemetryEventOneofCase.MultiplayerConnectionEvent) hash ^= MultiplayerConnectionEvent.GetHashCode();
      if (telemetryEventCase_ == TelemetryEventOneofCase.EnableContextualAwarenessEvent) hash ^= EnableContextualAwarenessEvent.GetHashCode();
      if (commonMetaData_ != null) hash ^= CommonMetaData.GetHashCode();
      if (DeveloperKey.Length != 0) hash ^= DeveloperKey.GetHashCode();
      if (timestamp_ != null) hash ^= Timestamp.GetHashCode();
      hash ^= (int) telemetryEventCase_;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (telemetryEventCase_ == TelemetryEventOneofCase.InitializationEvent) {
        output.WriteRawTag(10);
        output.WriteMessage(InitializationEvent);
      }
      if (telemetryEventCase_ == TelemetryEventOneofCase.ArSessionEvent) {
        output.WriteRawTag(18);
        output.WriteMessage(ArSessionEvent);
      }
      if (telemetryEventCase_ == TelemetryEventOneofCase.LightshipServiceEvent) {
        output.WriteRawTag(26);
        output.WriteMessage(LightshipServiceEvent);
      }
      if (telemetryEventCase_ == TelemetryEventOneofCase.MultiplayerConnectionEvent) {
        output.WriteRawTag(34);
        output.WriteMessage(MultiplayerConnectionEvent);
      }
      if (telemetryEventCase_ == TelemetryEventOneofCase.EnableContextualAwarenessEvent) {
        output.WriteRawTag(42);
        output.WriteMessage(EnableContextualAwarenessEvent);
      }
      if (commonMetaData_ != null) {
        output.WriteRawTag(194, 62);
        output.WriteMessage(CommonMetaData);
      }
      if (DeveloperKey.Length != 0) {
        output.WriteRawTag(202, 62);
        output.WriteString(DeveloperKey);
      }
      if (timestamp_ != null) {
        output.WriteRawTag(210, 62);
        output.WriteMessage(Timestamp);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (telemetryEventCase_ == TelemetryEventOneofCase.InitializationEvent) {
        output.WriteRawTag(10);
        output.WriteMessage(InitializationEvent);
      }
      if (telemetryEventCase_ == TelemetryEventOneofCase.ArSessionEvent) {
        output.WriteRawTag(18);
        output.WriteMessage(ArSessionEvent);
      }
      if (telemetryEventCase_ == TelemetryEventOneofCase.LightshipServiceEvent) {
        output.WriteRawTag(26);
        output.WriteMessage(LightshipServiceEvent);
      }
      if (telemetryEventCase_ == TelemetryEventOneofCase.MultiplayerConnectionEvent) {
        output.WriteRawTag(34);
        output.WriteMessage(MultiplayerConnectionEvent);
      }
      if (telemetryEventCase_ == TelemetryEventOneofCase.EnableContextualAwarenessEvent) {
        output.WriteRawTag(42);
        output.WriteMessage(EnableContextualAwarenessEvent);
      }
      if (commonMetaData_ != null) {
        output.WriteRawTag(194, 62);
        output.WriteMessage(CommonMetaData);
      }
      if (DeveloperKey.Length != 0) {
        output.WriteRawTag(202, 62);
        output.WriteString(DeveloperKey);
      }
      if (timestamp_ != null) {
        output.WriteRawTag(210, 62);
        output.WriteMessage(Timestamp);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (telemetryEventCase_ == TelemetryEventOneofCase.InitializationEvent) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(InitializationEvent);
      }
      if (telemetryEventCase_ == TelemetryEventOneofCase.ArSessionEvent) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ArSessionEvent);
      }
      if (telemetryEventCase_ == TelemetryEventOneofCase.LightshipServiceEvent) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(LightshipServiceEvent);
      }
      if (telemetryEventCase_ == TelemetryEventOneofCase.MultiplayerConnectionEvent) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(MultiplayerConnectionEvent);
      }
      if (telemetryEventCase_ == TelemetryEventOneofCase.EnableContextualAwarenessEvent) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(EnableContextualAwarenessEvent);
      }
      if (commonMetaData_ != null) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(CommonMetaData);
      }
      if (DeveloperKey.Length != 0) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(DeveloperKey);
      }
      if (timestamp_ != null) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(Timestamp);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ARDKTelemetryOmniProto other) {
      if (other == null) {
        return;
      }
      if (other.commonMetaData_ != null) {
        if (commonMetaData_ == null) {
          CommonMetaData = new global::Niantic.ARDK.AR.Protobuf.ARCommonMetadata();
        }
        CommonMetaData.MergeFrom(other.CommonMetaData);
      }
      if (other.DeveloperKey.Length != 0) {
        DeveloperKey = other.DeveloperKey;
      }
      if (other.timestamp_ != null) {
        if (timestamp_ == null) {
          Timestamp = new global::Google.Protobuf.WellKnownTypes.Timestamp();
        }
        Timestamp.MergeFrom(other.Timestamp);
      }
      switch (other.TelemetryEventCase) {
        case TelemetryEventOneofCase.InitializationEvent:
          if (InitializationEvent == null) {
            InitializationEvent = new global::Niantic.ARDK.AR.Protobuf.InitializationEvent();
          }
          InitializationEvent.MergeFrom(other.InitializationEvent);
          break;
        case TelemetryEventOneofCase.ArSessionEvent:
          if (ArSessionEvent == null) {
            ArSessionEvent = new global::Niantic.ARDK.AR.Protobuf.ARSessionEvent();
          }
          ArSessionEvent.MergeFrom(other.ArSessionEvent);
          break;
        case TelemetryEventOneofCase.LightshipServiceEvent:
          if (LightshipServiceEvent == null) {
            LightshipServiceEvent = new global::Niantic.ARDK.AR.Protobuf.LightshipServiceEvent();
          }
          LightshipServiceEvent.MergeFrom(other.LightshipServiceEvent);
          break;
        case TelemetryEventOneofCase.MultiplayerConnectionEvent:
          if (MultiplayerConnectionEvent == null) {
            MultiplayerConnectionEvent = new global::Niantic.ARDK.AR.Protobuf.MultiplayerConnectionEvent();
          }
          MultiplayerConnectionEvent.MergeFrom(other.MultiplayerConnectionEvent);
          break;
        case TelemetryEventOneofCase.EnableContextualAwarenessEvent:
          if (EnableContextualAwarenessEvent == null) {
            EnableContextualAwarenessEvent = new global::Niantic.ARDK.AR.Protobuf.EnabledContextualAwarenessEvent();
          }
          EnableContextualAwarenessEvent.MergeFrom(other.EnableContextualAwarenessEvent);
          break;
      }

      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            global::Niantic.ARDK.AR.Protobuf.InitializationEvent subBuilder = new global::Niantic.ARDK.AR.Protobuf.InitializationEvent();
            if (telemetryEventCase_ == TelemetryEventOneofCase.InitializationEvent) {
              subBuilder.MergeFrom(InitializationEvent);
            }
            input.ReadMessage(subBuilder);
            InitializationEvent = subBuilder;
            break;
          }
          case 18: {
            global::Niantic.ARDK.AR.Protobuf.ARSessionEvent subBuilder = new global::Niantic.ARDK.AR.Protobuf.ARSessionEvent();
            if (telemetryEventCase_ == TelemetryEventOneofCase.ArSessionEvent) {
              subBuilder.MergeFrom(ArSessionEvent);
            }
            input.ReadMessage(subBuilder);
            ArSessionEvent = subBuilder;
            break;
          }
          case 26: {
            global::Niantic.ARDK.AR.Protobuf.LightshipServiceEvent subBuilder = new global::Niantic.ARDK.AR.Protobuf.LightshipServiceEvent();
            if (telemetryEventCase_ == TelemetryEventOneofCase.LightshipServiceEvent) {
              subBuilder.MergeFrom(LightshipServiceEvent);
            }
            input.ReadMessage(subBuilder);
            LightshipServiceEvent = subBuilder;
            break;
          }
          case 34: {
            global::Niantic.ARDK.AR.Protobuf.MultiplayerConnectionEvent subBuilder = new global::Niantic.ARDK.AR.Protobuf.MultiplayerConnectionEvent();
            if (telemetryEventCase_ == TelemetryEventOneofCase.MultiplayerConnectionEvent) {
              subBuilder.MergeFrom(MultiplayerConnectionEvent);
            }
            input.ReadMessage(subBuilder);
            MultiplayerConnectionEvent = subBuilder;
            break;
          }
          case 42: {
            global::Niantic.ARDK.AR.Protobuf.EnabledContextualAwarenessEvent subBuilder = new global::Niantic.ARDK.AR.Protobuf.EnabledContextualAwarenessEvent();
            if (telemetryEventCase_ == TelemetryEventOneofCase.EnableContextualAwarenessEvent) {
              subBuilder.MergeFrom(EnableContextualAwarenessEvent);
            }
            input.ReadMessage(subBuilder);
            EnableContextualAwarenessEvent = subBuilder;
            break;
          }
          case 8002: {
            if (commonMetaData_ == null) {
              CommonMetaData = new global::Niantic.ARDK.AR.Protobuf.ARCommonMetadata();
            }
            input.ReadMessage(CommonMetaData);
            break;
          }
          case 8010: {
            DeveloperKey = input.ReadString();
            break;
          }
          case 8018: {
            if (timestamp_ == null) {
              Timestamp = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(Timestamp);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            global::Niantic.ARDK.AR.Protobuf.InitializationEvent subBuilder = new global::Niantic.ARDK.AR.Protobuf.InitializationEvent();
            if (telemetryEventCase_ == TelemetryEventOneofCase.InitializationEvent) {
              subBuilder.MergeFrom(InitializationEvent);
            }
            input.ReadMessage(subBuilder);
            InitializationEvent = subBuilder;
            break;
          }
          case 18: {
            global::Niantic.ARDK.AR.Protobuf.ARSessionEvent subBuilder = new global::Niantic.ARDK.AR.Protobuf.ARSessionEvent();
            if (telemetryEventCase_ == TelemetryEventOneofCase.ArSessionEvent) {
              subBuilder.MergeFrom(ArSessionEvent);
            }
            input.ReadMessage(subBuilder);
            ArSessionEvent = subBuilder;
            break;
          }
          case 26: {
            global::Niantic.ARDK.AR.Protobuf.LightshipServiceEvent subBuilder = new global::Niantic.ARDK.AR.Protobuf.LightshipServiceEvent();
            if (telemetryEventCase_ == TelemetryEventOneofCase.LightshipServiceEvent) {
              subBuilder.MergeFrom(LightshipServiceEvent);
            }
            input.ReadMessage(subBuilder);
            LightshipServiceEvent = subBuilder;
            break;
          }
          case 34: {
            global::Niantic.ARDK.AR.Protobuf.MultiplayerConnectionEvent subBuilder = new global::Niantic.ARDK.AR.Protobuf.MultiplayerConnectionEvent();
            if (telemetryEventCase_ == TelemetryEventOneofCase.MultiplayerConnectionEvent) {
              subBuilder.MergeFrom(MultiplayerConnectionEvent);
            }
            input.ReadMessage(subBuilder);
            MultiplayerConnectionEvent = subBuilder;
            break;
          }
          case 42: {
            global::Niantic.ARDK.AR.Protobuf.EnabledContextualAwarenessEvent subBuilder = new global::Niantic.ARDK.AR.Protobuf.EnabledContextualAwarenessEvent();
            if (telemetryEventCase_ == TelemetryEventOneofCase.EnableContextualAwarenessEvent) {
              subBuilder.MergeFrom(EnableContextualAwarenessEvent);
            }
            input.ReadMessage(subBuilder);
            EnableContextualAwarenessEvent = subBuilder;
            break;
          }
          case 8002: {
            if (commonMetaData_ == null) {
              CommonMetaData = new global::Niantic.ARDK.AR.Protobuf.ARCommonMetadata();
            }
            input.ReadMessage(CommonMetaData);
            break;
          }
          case 8010: {
            DeveloperKey = input.ReadString();
            break;
          }
          case 8018: {
            if (timestamp_ == null) {
              Timestamp = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(Timestamp);
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// Protobuf provides a mutable_ function to access the message members while set_ function to other members.
  /// They
  /// Note, since we are using macros to implement the telemetry events at ARDK, so that developers do not need
  /// to deal with constructing proto message. As Protobuf provides a mutable_ function to access the message members
  /// while set_ function to other members. As limitation, all the telemetry message can't be nested by another message
  /// for simplicity purpose..
  /// </summary>
  public sealed partial class InitializationEvent : pb::IMessage<InitializationEvent>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<InitializationEvent> _parser = new pb::MessageParser<InitializationEvent>(() => new InitializationEvent());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<InitializationEvent> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Niantic.ARDK.AR.Protobuf.ArdkTelemetryReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public InitializationEvent() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public InitializationEvent(InitializationEvent other) : this() {
      installMode_ = other.installMode_;
      localeRegion_ = other.localeRegion_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public InitializationEvent Clone() {
      return new InitializationEvent(this);
    }

    /// <summary>Field number for the "install_mode" field.</summary>
    public const int InstallModeFieldNumber = 1;
    private string installMode_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string InstallMode {
      get { return installMode_; }
      set {
        installMode_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "locale_region" field.</summary>
    public const int LocaleRegionFieldNumber = 2;
    private string localeRegion_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string LocaleRegion {
      get { return localeRegion_; }
      set {
        localeRegion_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as InitializationEvent);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(InitializationEvent other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (InstallMode != other.InstallMode) return false;
      if (LocaleRegion != other.LocaleRegion) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (InstallMode.Length != 0) hash ^= InstallMode.GetHashCode();
      if (LocaleRegion.Length != 0) hash ^= LocaleRegion.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (InstallMode.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(InstallMode);
      }
      if (LocaleRegion.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(LocaleRegion);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (InstallMode.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(InstallMode);
      }
      if (LocaleRegion.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(LocaleRegion);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (InstallMode.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(InstallMode);
      }
      if (LocaleRegion.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(LocaleRegion);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(InitializationEvent other) {
      if (other == null) {
        return;
      }
      if (other.InstallMode.Length != 0) {
        InstallMode = other.InstallMode;
      }
      if (other.LocaleRegion.Length != 0) {
        LocaleRegion = other.LocaleRegion;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            InstallMode = input.ReadString();
            break;
          }
          case 18: {
            LocaleRegion = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            InstallMode = input.ReadString();
            break;
          }
          case 18: {
            LocaleRegion = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class ARSessionEvent : pb::IMessage<ARSessionEvent>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ARSessionEvent> _parser = new pb::MessageParser<ARSessionEvent>(() => new ARSessionEvent());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ARSessionEvent> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Niantic.ARDK.AR.Protobuf.ArdkTelemetryReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ARSessionEvent() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ARSessionEvent(ARSessionEvent other) : this() {
      sessionState_ = other.sessionState_;
      sessionId_ = other.sessionId_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ARSessionEvent Clone() {
      return new ARSessionEvent(this);
    }

    /// <summary>Field number for the "session_state" field.</summary>
    public const int SessionStateFieldNumber = 1;
    private global::Niantic.ARDK.AR.Protobuf.ARSessionEvent.Types.State sessionState_ = global::Niantic.ARDK.AR.Protobuf.ARSessionEvent.Types.State.Unknown;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Niantic.ARDK.AR.Protobuf.ARSessionEvent.Types.State SessionState {
      get { return sessionState_; }
      set {
        sessionState_ = value;
      }
    }

    /// <summary>Field number for the "session_id" field.</summary>
    public const int SessionIdFieldNumber = 2;
    private string sessionId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string SessionId {
      get { return sessionId_; }
      set {
        sessionId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ARSessionEvent);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ARSessionEvent other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (SessionState != other.SessionState) return false;
      if (SessionId != other.SessionId) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (SessionState != global::Niantic.ARDK.AR.Protobuf.ARSessionEvent.Types.State.Unknown) hash ^= SessionState.GetHashCode();
      if (SessionId.Length != 0) hash ^= SessionId.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (SessionState != global::Niantic.ARDK.AR.Protobuf.ARSessionEvent.Types.State.Unknown) {
        output.WriteRawTag(8);
        output.WriteEnum((int) SessionState);
      }
      if (SessionId.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(SessionId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (SessionState != global::Niantic.ARDK.AR.Protobuf.ARSessionEvent.Types.State.Unknown) {
        output.WriteRawTag(8);
        output.WriteEnum((int) SessionState);
      }
      if (SessionId.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(SessionId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (SessionState != global::Niantic.ARDK.AR.Protobuf.ARSessionEvent.Types.State.Unknown) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) SessionState);
      }
      if (SessionId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(SessionId);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ARSessionEvent other) {
      if (other == null) {
        return;
      }
      if (other.SessionState != global::Niantic.ARDK.AR.Protobuf.ARSessionEvent.Types.State.Unknown) {
        SessionState = other.SessionState;
      }
      if (other.SessionId.Length != 0) {
        SessionId = other.SessionId;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            SessionState = (global::Niantic.ARDK.AR.Protobuf.ARSessionEvent.Types.State) input.ReadEnum();
            break;
          }
          case 18: {
            SessionId = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            SessionState = (global::Niantic.ARDK.AR.Protobuf.ARSessionEvent.Types.State) input.ReadEnum();
            break;
          }
          case 18: {
            SessionId = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the ARSessionEvent message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      public enum State {
        [pbr::OriginalName("UNKNOWN")] Unknown = 0,
        [pbr::OriginalName("CREATED")] Created = 1,
        [pbr::OriginalName("RUN")] Run = 2,
        [pbr::OriginalName("PAUSE")] Pause = 3,
        [pbr::OriginalName("DISPOSED")] Disposed = 4,
      }

    }
    #endregion

  }

  public sealed partial class LightshipServiceEvent : pb::IMessage<LightshipServiceEvent>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<LightshipServiceEvent> _parser = new pb::MessageParser<LightshipServiceEvent>(() => new LightshipServiceEvent());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<LightshipServiceEvent> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Niantic.ARDK.AR.Protobuf.ArdkTelemetryReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public LightshipServiceEvent() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public LightshipServiceEvent(LightshipServiceEvent other) : this() {
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public LightshipServiceEvent Clone() {
      return new LightshipServiceEvent(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as LightshipServiceEvent);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(LightshipServiceEvent other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(LightshipServiceEvent other) {
      if (other == null) {
        return;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
        }
      }
    }
    #endif

  }

  public sealed partial class MultiplayerConnectionEvent : pb::IMessage<MultiplayerConnectionEvent>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<MultiplayerConnectionEvent> _parser = new pb::MessageParser<MultiplayerConnectionEvent>(() => new MultiplayerConnectionEvent());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<MultiplayerConnectionEvent> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Niantic.ARDK.AR.Protobuf.ArdkTelemetryReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MultiplayerConnectionEvent() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MultiplayerConnectionEvent(MultiplayerConnectionEvent other) : this() {
      connection_ = other.connection_;
      arbeSesssionInstanceId_ = other.arbeSesssionInstanceId_;
      sessionId_ = other.sessionId_;
      peerState_ = other.peerState_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MultiplayerConnectionEvent Clone() {
      return new MultiplayerConnectionEvent(this);
    }

    /// <summary>Field number for the "connection" field.</summary>
    public const int ConnectionFieldNumber = 1;
    private global::Niantic.ARDK.AR.Protobuf.MultiplayerConnectionEvent.Types.ConnectState connection_ = global::Niantic.ARDK.AR.Protobuf.MultiplayerConnectionEvent.Types.ConnectState.Unknown;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Niantic.ARDK.AR.Protobuf.MultiplayerConnectionEvent.Types.ConnectState Connection {
      get { return connection_; }
      set {
        connection_ = value;
      }
    }

    /// <summary>Field number for the "arbe_sesssion_instance_id" field.</summary>
    public const int ArbeSesssionInstanceIdFieldNumber = 2;
    private string arbeSesssionInstanceId_ = "";
    /// <summary>
    /// server generated session ID
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ArbeSesssionInstanceId {
      get { return arbeSesssionInstanceId_; }
      set {
        arbeSesssionInstanceId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "session_id" field.</summary>
    public const int SessionIdFieldNumber = 3;
    private string sessionId_ = "";
    /// <summary>
    /// client generated session ID for ARDK 1.0
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string SessionId {
      get { return sessionId_; }
      set {
        sessionId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "peer_state" field.</summary>
    public const int PeerStateFieldNumber = 4;
    private global::Niantic.ARDK.AR.Protobuf.MultiplayerConnectionEvent.Types.PeerState peerState_ = global::Niantic.ARDK.AR.Protobuf.MultiplayerConnectionEvent.Types.PeerState.StateUnknown;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Niantic.ARDK.AR.Protobuf.MultiplayerConnectionEvent.Types.PeerState PeerState {
      get { return peerState_; }
      set {
        peerState_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as MultiplayerConnectionEvent);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(MultiplayerConnectionEvent other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Connection != other.Connection) return false;
      if (ArbeSesssionInstanceId != other.ArbeSesssionInstanceId) return false;
      if (SessionId != other.SessionId) return false;
      if (PeerState != other.PeerState) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Connection != global::Niantic.ARDK.AR.Protobuf.MultiplayerConnectionEvent.Types.ConnectState.Unknown) hash ^= Connection.GetHashCode();
      if (ArbeSesssionInstanceId.Length != 0) hash ^= ArbeSesssionInstanceId.GetHashCode();
      if (SessionId.Length != 0) hash ^= SessionId.GetHashCode();
      if (PeerState != global::Niantic.ARDK.AR.Protobuf.MultiplayerConnectionEvent.Types.PeerState.StateUnknown) hash ^= PeerState.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Connection != global::Niantic.ARDK.AR.Protobuf.MultiplayerConnectionEvent.Types.ConnectState.Unknown) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Connection);
      }
      if (ArbeSesssionInstanceId.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(ArbeSesssionInstanceId);
      }
      if (SessionId.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(SessionId);
      }
      if (PeerState != global::Niantic.ARDK.AR.Protobuf.MultiplayerConnectionEvent.Types.PeerState.StateUnknown) {
        output.WriteRawTag(32);
        output.WriteEnum((int) PeerState);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Connection != global::Niantic.ARDK.AR.Protobuf.MultiplayerConnectionEvent.Types.ConnectState.Unknown) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Connection);
      }
      if (ArbeSesssionInstanceId.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(ArbeSesssionInstanceId);
      }
      if (SessionId.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(SessionId);
      }
      if (PeerState != global::Niantic.ARDK.AR.Protobuf.MultiplayerConnectionEvent.Types.PeerState.StateUnknown) {
        output.WriteRawTag(32);
        output.WriteEnum((int) PeerState);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Connection != global::Niantic.ARDK.AR.Protobuf.MultiplayerConnectionEvent.Types.ConnectState.Unknown) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Connection);
      }
      if (ArbeSesssionInstanceId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ArbeSesssionInstanceId);
      }
      if (SessionId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(SessionId);
      }
      if (PeerState != global::Niantic.ARDK.AR.Protobuf.MultiplayerConnectionEvent.Types.PeerState.StateUnknown) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) PeerState);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(MultiplayerConnectionEvent other) {
      if (other == null) {
        return;
      }
      if (other.Connection != global::Niantic.ARDK.AR.Protobuf.MultiplayerConnectionEvent.Types.ConnectState.Unknown) {
        Connection = other.Connection;
      }
      if (other.ArbeSesssionInstanceId.Length != 0) {
        ArbeSesssionInstanceId = other.ArbeSesssionInstanceId;
      }
      if (other.SessionId.Length != 0) {
        SessionId = other.SessionId;
      }
      if (other.PeerState != global::Niantic.ARDK.AR.Protobuf.MultiplayerConnectionEvent.Types.PeerState.StateUnknown) {
        PeerState = other.PeerState;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Connection = (global::Niantic.ARDK.AR.Protobuf.MultiplayerConnectionEvent.Types.ConnectState) input.ReadEnum();
            break;
          }
          case 18: {
            ArbeSesssionInstanceId = input.ReadString();
            break;
          }
          case 26: {
            SessionId = input.ReadString();
            break;
          }
          case 32: {
            PeerState = (global::Niantic.ARDK.AR.Protobuf.MultiplayerConnectionEvent.Types.PeerState) input.ReadEnum();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Connection = (global::Niantic.ARDK.AR.Protobuf.MultiplayerConnectionEvent.Types.ConnectState) input.ReadEnum();
            break;
          }
          case 18: {
            ArbeSesssionInstanceId = input.ReadString();
            break;
          }
          case 26: {
            SessionId = input.ReadString();
            break;
          }
          case 32: {
            PeerState = (global::Niantic.ARDK.AR.Protobuf.MultiplayerConnectionEvent.Types.PeerState) input.ReadEnum();
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the MultiplayerConnectionEvent message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      public enum ConnectState {
        [pbr::OriginalName("UNKNOWN")] Unknown = 0,
        [pbr::OriginalName("START")] Start = 1,
        [pbr::OriginalName("JOIN")] Join = 2,
        [pbr::OriginalName("CONNECTED")] Connected = 3,
        [pbr::OriginalName("LEAVE")] Leave = 4,
        [pbr::OriginalName("END")] End = 5,
      }

      public enum PeerState {
        [pbr::OriginalName("STATE_UNKNOWN")] StateUnknown = 0,
        [pbr::OriginalName("INITIALIZING")] Initializing = 1,
        [pbr::OriginalName("WAITING_FOR_LOCALIZATION_DATA")] WaitingForLocalizationData = 2,
        [pbr::OriginalName("LOCALIZING")] Localizing = 3,
        [pbr::OriginalName("STABILIZING")] Stabilizing = 4,
        [pbr::OriginalName("STABLE")] Stable = 5,
        [pbr::OriginalName("LIMITED")] Limited = 6,
        [pbr::OriginalName("FAILED")] Failed = 7,
      }

    }
    #endregion

  }

  public sealed partial class EnabledContextualAwarenessEvent : pb::IMessage<EnabledContextualAwarenessEvent>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<EnabledContextualAwarenessEvent> _parser = new pb::MessageParser<EnabledContextualAwarenessEvent>(() => new EnabledContextualAwarenessEvent());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<EnabledContextualAwarenessEvent> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Niantic.ARDK.AR.Protobuf.ArdkTelemetryReflection.Descriptor.MessageTypes[5]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public EnabledContextualAwarenessEvent() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public EnabledContextualAwarenessEvent(EnabledContextualAwarenessEvent other) : this() {
      meshing_ = other.meshing_;
      fusion_ = other.fusion_;
      depth_ = other.depth_;
      semantics_ = other.semantics_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public EnabledContextualAwarenessEvent Clone() {
      return new EnabledContextualAwarenessEvent(this);
    }

    /// <summary>Field number for the "meshing" field.</summary>
    public const int MeshingFieldNumber = 1;
    private bool meshing_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Meshing {
      get { return meshing_; }
      set {
        meshing_ = value;
      }
    }

    /// <summary>Field number for the "fusion" field.</summary>
    public const int FusionFieldNumber = 2;
    private bool fusion_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Fusion {
      get { return fusion_; }
      set {
        fusion_ = value;
      }
    }

    /// <summary>Field number for the "depth" field.</summary>
    public const int DepthFieldNumber = 3;
    private bool depth_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Depth {
      get { return depth_; }
      set {
        depth_ = value;
      }
    }

    /// <summary>Field number for the "semantics" field.</summary>
    public const int SemanticsFieldNumber = 4;
    private bool semantics_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Semantics {
      get { return semantics_; }
      set {
        semantics_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as EnabledContextualAwarenessEvent);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(EnabledContextualAwarenessEvent other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Meshing != other.Meshing) return false;
      if (Fusion != other.Fusion) return false;
      if (Depth != other.Depth) return false;
      if (Semantics != other.Semantics) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Meshing != false) hash ^= Meshing.GetHashCode();
      if (Fusion != false) hash ^= Fusion.GetHashCode();
      if (Depth != false) hash ^= Depth.GetHashCode();
      if (Semantics != false) hash ^= Semantics.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Meshing != false) {
        output.WriteRawTag(8);
        output.WriteBool(Meshing);
      }
      if (Fusion != false) {
        output.WriteRawTag(16);
        output.WriteBool(Fusion);
      }
      if (Depth != false) {
        output.WriteRawTag(24);
        output.WriteBool(Depth);
      }
      if (Semantics != false) {
        output.WriteRawTag(32);
        output.WriteBool(Semantics);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Meshing != false) {
        output.WriteRawTag(8);
        output.WriteBool(Meshing);
      }
      if (Fusion != false) {
        output.WriteRawTag(16);
        output.WriteBool(Fusion);
      }
      if (Depth != false) {
        output.WriteRawTag(24);
        output.WriteBool(Depth);
      }
      if (Semantics != false) {
        output.WriteRawTag(32);
        output.WriteBool(Semantics);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Meshing != false) {
        size += 1 + 1;
      }
      if (Fusion != false) {
        size += 1 + 1;
      }
      if (Depth != false) {
        size += 1 + 1;
      }
      if (Semantics != false) {
        size += 1 + 1;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(EnabledContextualAwarenessEvent other) {
      if (other == null) {
        return;
      }
      if (other.Meshing != false) {
        Meshing = other.Meshing;
      }
      if (other.Fusion != false) {
        Fusion = other.Fusion;
      }
      if (other.Depth != false) {
        Depth = other.Depth;
      }
      if (other.Semantics != false) {
        Semantics = other.Semantics;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Meshing = input.ReadBool();
            break;
          }
          case 16: {
            Fusion = input.ReadBool();
            break;
          }
          case 24: {
            Depth = input.ReadBool();
            break;
          }
          case 32: {
            Semantics = input.ReadBool();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Meshing = input.ReadBool();
            break;
          }
          case 16: {
            Fusion = input.ReadBool();
            break;
          }
          case 24: {
            Depth = input.ReadBool();
            break;
          }
          case 32: {
            Semantics = input.ReadBool();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
